/**
 * ops/publish/export/zipBuilder.ts
 *
 * Builds a ZIP-like export package from artifact entries.
 * Uses an in-memory representation (no real zip library dependency).
 * Production adapters can wrap JSZip or archiver.
 *
 * The "ZIP" is represented as a ZipPackage with entries and metadata.
 * This keeps the module dependency-free and testable.
 */

import type { ExportManifest, ExportManifestEntry } from './exportManifest.js'
import { buildExportManifest } from './exportManifest.js'

/** A single file in the ZIP package. */
export interface ZipEntry {
  readonly path: string
  readonly content: string
  readonly sha256: string
  readonly size: number
}

/** The complete ZIP package (in-memory representation). */
export interface ZipPackage {
  readonly filename: string
  readonly entries: readonly ZipEntry[]
  readonly manifest: ExportManifest
  readonly generationMeta: GenerationMeta
  readonly totalSize: number
  readonly disclaimer?: string
}

/** Sanitized generation metadata (no secrets). */
export interface GenerationMeta {
  readonly siteId: string
  readonly blueprintId: string
  readonly generatedAt: string
  readonly exportedAt: string
  readonly correlationId: string
  readonly watermarked: boolean
  readonly demoMode: boolean
  readonly artifactCount: number
}

/** ZIP builder configuration. */
export interface ZipBuilderConfig {
  /** Maximum total ZIP size in bytes. Default: 50MB. */
  readonly maxTotalSize: number
  /** Hash function for manifest generation. */
  readonly hashFn: (input: string) => string
}

const DEFAULT_MAX_SIZE = 50 * 1024 * 1024 // 50 MB

/**
 * Build a ZIP package from artifacts and metadata.
 * Demo exports include a disclaimer file.
 */
export function buildZipPackage(
  siteId: string,
  blueprintId: string,
  generatedAt: string,
  correlationId: string,
  watermarked: boolean,
  demoMode: boolean,
  artifacts: readonly ZipEntry[],
  config: Partial<ZipBuilderConfig> = {},
): ZipPackage | { error: string } {
  const maxSize = config.maxTotalSize ?? DEFAULT_MAX_SIZE
  const hashFn = config.hashFn ?? djb2Hash

  // Calculate total size
  const totalSize = artifacts.reduce((sum, a) => sum + a.size, 0)
  if (totalSize > maxSize) {
    return { error: `ZIP size ${totalSize} exceeds maximum ${maxSize}` }
  }

  // Build entries list (artifacts + meta files)
  const entries: ZipEntry[] = [...artifacts]

  // Build manifest
  const manifestEntries: ExportManifestEntry[] = artifacts.map(a => ({
    path: a.path,
    sha256: a.sha256,
    size: a.size,
  }))
  const manifest = buildExportManifest(
    siteId, blueprintId, generatedAt, correlationId,
    watermarked, demoMode, manifestEntries, hashFn,
  )

  const manifestJson = JSON.stringify(manifest, null, 2)
  entries.push({
    path: 'manifest.json',
    content: manifestJson,
    sha256: hashFn(manifestJson),
    size: manifestJson.length,
  })

  // Generation metadata (sanitized — no secrets)
  const genMeta: GenerationMeta = {
    siteId,
    blueprintId,
    generatedAt,
    exportedAt: manifest.exportedAt,
    correlationId,
    watermarked,
    demoMode,
    artifactCount: artifacts.length,
  }

  const metaJson = JSON.stringify(genMeta, null, 2)
  entries.push({
    path: 'generation.meta.json',
    content: metaJson,
    sha256: hashFn(metaJson),
    size: metaJson.length,
  })

  // Demo disclaimer
  let disclaimer: string | undefined
  if (demoMode) {
    disclaimer = DEMO_DISCLAIMER
    entries.push({
      path: 'DEMO_DISCLAIMER.txt',
      content: disclaimer,
      sha256: hashFn(disclaimer),
      size: disclaimer.length,
    })
  }

  const filename = `${siteId}_${manifest.manifestHash.slice(0, 8)}.zip`

  return {
    filename,
    entries,
    manifest,
    generationMeta: genMeta,
    totalSize: entries.reduce((sum, e) => sum + e.size, 0),
    disclaimer,
  }
}

const DEMO_DISCLAIMER = `DEMO EXPORT NOTICE
==================

This export was generated in demo mode around the Evident / XTX396 platform.

- This site package includes watermarks.
- This export is not intended for production use.
- All artifacts are provided as-is for evaluation purposes.
- No legal advice or guarantees are implied.

Generated by the Evident Technologies site generation pipeline.
`

/** DJB2 hash function (non-cryptographic, deterministic). */
function djb2Hash(input: string): string {
  let hash = 5381
  for (let i = 0; i < input.length; i++) {
    hash = ((hash << 5) + hash + input.charCodeAt(i)) >>> 0
  }
  return hash.toString(16).padStart(8, '0')
}
