/**
 * Case Jacket System — AI Summary Adapter
 *
 * Provides a pluggable interface for AI summary generation.
 * The default adapter is a mock that produces deterministic, labeled output.
 *
 * Invariants:
 * - All summaries include an explicit disclaimer.
 * - Summary generation is deterministic (same input → same output).
 * - The adapter never modifies evidence or case state.
 * - Summaries always cite source evidence IDs.
 */

import type { AISummary, EvidenceItem } from './types'

// ─── Adapter Interface ───────────────────────────────────────

/**
 * Interface for AI summary adapters.
 * Implementations must produce deterministic, disclaimered output.
 */
export interface AISummaryAdapterInterface {
  /** Adapter identifier. */
  readonly adapterId: string
  /** Generate a summary from evidence items. */
  generateSummary(
    caseId: string,
    evidence: readonly EvidenceItem[],
  ): Promise<AISummary>
}

// ─── Mock Adapter (Default) ──────────────────────────────────

/**
 * Mock AI summary adapter for testing and demo.
 * Produces deterministic output from evidence metadata.
 * No external API calls. No nondeterminism.
 */
export class MockAISummaryAdapter implements AISummaryAdapterInterface {
  readonly adapterId = 'mock-ai-v1'

  private static readonly DISCLAIMER =
    'This summary was generated by an automated system. ' +
    'It is not legal advice and must be independently verified. ' +
    'Do not rely on this summary for legal decisions.'

  async generateSummary(
    caseId: string,
    evidence: readonly EvidenceItem[],
  ): Promise<AISummary> {
    const sourceIds = evidence.map((e) => e.evidenceId)
    const evidenceDescriptions = evidence
      .map((e) => `- [${e.type}] ${e.label}: ${e.description}`)
      .join('\n')

    const summaryText = [
      `Case ${caseId} contains ${evidence.length} evidence item(s).`,
      '',
      'Evidence index:',
      evidenceDescriptions,
      '',
      `Total evidence types: ${new Set(evidence.map((e) => e.type)).size}.`,
      `Total evidence size: ${evidence.reduce((sum, e) => sum + e.size, 0)} bytes.`,
    ].join('\n')

    const now = new Date().toISOString()
    const summaryId = `sum_${caseId}_${sourceIds.length}_${this.adapterId}`

    return {
      summaryId,
      caseId,
      generatedBy: this.adapterId,
      generatedAt: now,
      content: summaryText,
      sourceEvidenceIds: sourceIds,
      confidence: 0.85,
      disclaimer: MockAISummaryAdapter.DISCLAIMER,
    }
  }
}
