/**
 * ops/publish/targets/GitHubPrPublishTarget.ts
 *
 * GitHub PR publish target — optional, disabled by default.
 * Opens a PR into an allowlisted repo via a GitHub App installation token.
 *
 * SECURITY:
 * - Blocked in Safe Mode
 * - Blocked for public-demo and trial tenants
 * - Requires repo allowlist
 * - Requires GitHub App configuration
 * - No secrets committed or printed
 * - PR body redacted before submission
 */

import type { PublishTarget, PublishTargetRegistration, CanPublishResult } from './PublishTarget.js'
import type { PublishRequest } from '../models/PublishRequest.js'
import type { PublishResult } from '../models/PublishResult.js'
import type { ArtifactBundle } from './HostedPublishTarget.js'
import type { GitHubApiAdapter, GitHubFileEntry } from '../../integrations/github/GitHubIntegration.js'
import { redactPrBody } from '../../integrations/github/GitHubIntegration.js'
import { RepoAllowlist } from '../../integrations/github/RepoAllowlist.js'

export interface GitHubPrPublishConfig {
  readonly targetRepo: string
  readonly baseBranch: string
  readonly branchPrefix: string
  readonly allowedRepos: readonly string[]
}

export class GitHubPrPublishTarget implements PublishTarget {
  readonly registration: PublishTargetRegistration

  private readonly _adapter: GitHubApiAdapter
  private readonly _allowlist: RepoAllowlist
  private readonly _config: GitHubPrPublishConfig
  private readonly _bundles: Map<string, ArtifactBundle>

  constructor(
    adapter: GitHubApiAdapter,
    config: GitHubPrPublishConfig,
    bundles?: Map<string, ArtifactBundle>,
  ) {
    this._adapter = adapter
    this._config = config
    this._allowlist = new RepoAllowlist({ allowedRepos: config.allowedRepos })
    this._bundles = bundles ?? new Map()

    this.registration = {
      id: 'github-pr',
      name: 'GitHub PR Publish',
      kind: 'github_pr',
      enabled: this._allowlist.size > 0 && adapter.isConfigured(),
      safeModeAllowed: false,
      requiredCapabilities: ['publish_site', 'manage_deployments'],
      blockedTenantTypes: ['public-demo', 'trial', 'suspended'],
      config: {
        targetRepo: config.targetRepo,
        baseBranch: config.baseBranch,
        allowedRepoCount: this._allowlist.size,
      },
    }
  }

  /** Register a bundle for a site. */
  registerBundle(artifactRef: string, bundle: ArtifactBundle): void {
    this._bundles.set(artifactRef, bundle)
  }

  canPublish(request: PublishRequest): CanPublishResult {
    if (!this._adapter.isConfigured()) {
      return { allowed: false, reason: 'GitHub App is not configured' }
    }

    if (this._allowlist.isEmpty) {
      return { allowed: false, reason: 'No repositories in allowlist' }
    }

    if (!this._allowlist.isAllowed(this._config.targetRepo)) {
      return { allowed: false, reason: `Repository '${this._config.targetRepo}' not in allowlist` }
    }

    return { allowed: true }
  }

  async publish(request: PublishRequest): Promise<PublishResult> {
    const bundle = this._bundles.get(request.artifactRef)
    if (!bundle) {
      return this._fail(request, `Artifact bundle not found: ${request.artifactRef}`)
    }

    // Enforce watermark in demo mode
    if (request.mode === 'demo' && !bundle.watermarked) {
      return this._fail(request, 'Demo mode requires watermarked artifacts')
    }

    // Generate branch name
    const timestamp = request.requestedAt.replace(/[-:T.Z]/g, '').slice(0, 14)
    const headBranch = `${this._config.branchPrefix}${request.siteId}-${timestamp}`

    // Build file entries for the PR
    const files: GitHubFileEntry[] = bundle.artifacts.map(a => ({
      path: `sites/${request.siteId}/${a.path}`,
      content: a.content,
    }))

    // Add manifest as a file in the PR
    const manifestContent = JSON.stringify({
      siteId: request.siteId,
      blueprintId: request.blueprintId,
      manifestHash: bundle.manifestHash,
      correlationId: request.correlationId,
      generatedAt: bundle.generatedAt,
      publishedAt: new Date().toISOString(),
      watermarked: bundle.watermarked,
    }, null, 2)
    files.push({ path: `sites/${request.siteId}/manifest.json`, content: manifestContent })

    // Build PR body (redacted to prevent secret leaks)
    const rawBody = [
      `## Site Publish: ${request.siteId}`,
      '',
      `| Field | Value |`,
      `|-------|-------|`,
      `| Site ID | ${request.siteId} |`,
      `| Blueprint | ${request.blueprintId} |`,
      `| Manifest Hash | \`${bundle.manifestHash}\` |`,
      `| Correlation ID | \`${request.correlationId}\` |`,
      `| Tenant | ${request.tenantId} |`,
      `| Actor | ${request.actorId} |`,
      `| Mode | ${request.mode} |`,
      '',
      '---',
      '*Generated by the Evident Technologies publish pipeline.*',
    ].join('\n')

    const body = redactPrBody(rawBody)

    const response = await this._adapter.createPullRequest({
      repo: this._config.targetRepo,
      baseBranch: this._config.baseBranch,
      headBranch,
      title: `[B22] Publish site: ${request.siteId}`,
      body,
      files,
    })

    if (!response.success) {
      return this._fail(request, response.error ?? 'GitHub PR creation failed')
    }

    return {
      success: true,
      target: 'github_pr',
      siteId: request.siteId,
      correlationId: request.correlationId,
      manifestHash: bundle.manifestHash,
      publishedAt: new Date().toISOString(),
      version: headBranch,
      prUrl: response.prUrl,
      auditEvents: [],
    }
  }

  private _fail(request: PublishRequest, error: string): PublishResult {
    return {
      success: false,
      target: 'github_pr',
      siteId: request.siteId,
      correlationId: request.correlationId,
      manifestHash: '',
      publishedAt: new Date().toISOString(),
      version: '',
      error,
      auditEvents: [],
    }
  }
}
