/**
 * Pipeline Step: Render
 *
 * Takes scaffolded pages and produces HTML output.
 * This is a deterministic, template-based renderer —
 * no randomness, no external API calls.
 */

import type {
  ScaffoldResult,
  RenderResult,
  RenderedPage,
  RenderedAsset,
} from './types'

// ─── Render ──────────────────────────────────────────────────

/**
 * Renders scaffolded pages into HTML strings.
 *
 * In production, this would use a full template engine.
 * This implementation produces deterministic HTML structures
 * suitable for hashing and integrity verification.
 */
export function render(scaffold: ScaffoldResult): RenderResult {
  const pages: RenderedPage[] = scaffold.pages.map((page) => {
    const sectionsHtml = page.sections
      .map(
        (s) =>
          `<section id="${escapeAttr(s.id)}" data-component="${escapeAttr(s.component)}">\n` +
          `  <div class="section-content">${escapeHtml(s.content)}</div>\n` +
          `</section>`,
      )
      .join('\n')

    const html =
      `<!DOCTYPE html>\n` +
      `<html lang="en">\n` +
      `<head>\n` +
      `  <meta charset="UTF-8">\n` +
      `  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n` +
      `  <title>${escapeHtml(page.title)} — ${escapeHtml(scaffold.metadata.businessName)}</title>\n` +
      `  <meta name="generator" content="XTX396 SiteGen v${escapeAttr(scaffold.metadata.blueprintVersion)}">\n` +
      `  <link rel="stylesheet" href="/assets/styles.css">\n` +
      `</head>\n` +
      `<body>\n` +
      `<main>\n` +
      `${sectionsHtml}\n` +
      `</main>\n` +
      `<script src="/assets/main.js" defer></script>\n` +
      `</body>\n` +
      `</html>`

    return { slug: page.slug, title: page.title, html }
  })

  // Generate base assets
  const assets: RenderedAsset[] = [
    {
      path: '/assets/styles.css',
      content: generateBaseCSS(scaffold.metadata.presetId),
      type: 'css',
    },
    {
      path: '/assets/main.js',
      content: generateBaseJS(),
      type: 'js',
    },
    {
      path: '/manifest.json',
      content: JSON.stringify(
        {
          blueprint: scaffold.metadata.blueprintId,
          version: scaffold.metadata.blueprintVersion,
          preset: scaffold.metadata.presetId,
          generatedAt: scaffold.metadata.generatedAt,
          pages: pages.map((p) => p.slug),
        },
        null,
        2,
      ),
      type: 'json',
    },
  ]

  return { pages, assets }
}

// ─── Helpers ─────────────────────────────────────────────────

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function escapeAttr(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function generateBaseCSS(presetId: string): string {
  return [
    `/* Generated by XTX396 SiteGen — preset: ${presetId} */`,
    ':root { --font-family: system-ui, sans-serif; --max-width: 1200px; }',
    'body { font-family: var(--font-family); margin: 0; padding: 0; }',
    'main { max-width: var(--max-width); margin: 0 auto; padding: 1rem; }',
    '.section-content { margin-block: 2rem; }',
  ].join('\n')
}

function generateBaseJS(): string {
  return [
    '/* Generated by XTX396 SiteGen — minimal base script */',
    '"use strict";',
    'document.addEventListener("DOMContentLoaded", function() {',
    '  console.log("[SiteGen] Page loaded.");',
    '});',
  ].join('\n')
}
